-- SUPABASE SQL SETUP SCRIPT
-- Copy and paste this script into your Supabase Dashboard SQL Editor (https://supabase.com)
-- to automatically create all the tables and setup real-time subscriptions!

-- 1. Create the settings table for saving the dynamic configurations
CREATE TABLE IF NOT EXISTS public.settings (
    id TEXT PRIMARY KEY,
    data JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the rsvps table for capturing event registrations
CREATE TABLE IF NOT EXISTS public.rsvps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    guests_count INTEGER DEFAULT 0,
    guestsCount INTEGER DEFAULT 0, -- Support both camelCase and snake_case
    attend BOOLEAN DEFAULT TRUE,
    message TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create the fs_files table for background audio and image upload chunks
CREATE TABLE IF NOT EXISTS public.fs_files (
    id TEXT PRIMARY KEY, -- chunkId (e.g. fileId_index)
    fileId TEXT NOT NULL,
    index INTEGER NOT NULL,
    data TEXT NOT NULL, -- Base64 data chunk
    totalChunks INTEGER NOT NULL,
    createdAt TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Disable Row Level Security (RLS) for public access or configure policy:
-- Note: For simple event invitations, you can disable RLS or allow all reads/writes.
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.rsvps DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.fs_files DISABLE ROW LEVEL SECURITY;

-- 5. Insert initial empty config if not exists to avoid empty states
INSERT INTO public.settings (id, data)
VALUES ('config', '{}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- 6. Enable Realtime for the tables safely
-- We use separate PL/pgSQL DO blocks to handle 'duplicate_object' (42710)
-- exceptions, meaning they won't halt execution if the table is already in the publication!
DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.settings;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'settings table is already in publication.';
    WHEN OTHERS THEN
        RAISE NOTICE 'Could not add settings to publication: %', SQLERRM;
END $$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.rsvps;
EXCEPTION
    WHEN duplicate_object THEN
        RAISE NOTICE 'rsvps table is already in publication.';
    WHEN OTHERS THEN
        RAISE NOTICE 'Could not add rsvps to publication: %', SQLERRM;
END $$;
